# Generated by Django 6.0.2 on 2026-02-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "country",
                    models.CharField(
                        choices=[
                            ("china", "Китай"),
                            ("korea", "Корея"),
                            ("usa", "США"),
                        ],
                        max_length=20,
                        verbose_name="Страна",
                    ),
                ),
                ("budget", models.CharField(max_length=50, verbose_name="Бюджет (₽)")),
                (
                    "body_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Любой"),
                            ("sedan", "Седан"),
                            ("suv", "Внедорожник"),
                            ("coupe", "Купе"),
                            ("minivan", "Минивэн"),
                            ("pickup", "Пикап"),
                            ("hatchback", "Хэтчбек"),
                        ],
                        default="",
                        max_length=20,
                        verbose_name="Тип кузова",
                    ),
                ),
                (
                    "urgency",
                    models.CharField(
                        choices=[("normal", "Обычная"), ("fast", "Срочно")],
                        default="normal",
                        max_length=20,
                        verbose_name="Срочность",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Имя")),
                ("phone", models.CharField(max_length=30, verbose_name="Телефон")),
                (
                    "contact",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Telegram или WhatsApp"
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
            ],
            options={
                "verbose_name": "Заявка",
                "verbose_name_plural": "Заявки",
                "ordering": ["-created_at"],
            },
        ),
    ]
