# Generated by Django 5.2.7 on 2026-03-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarSearchRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Имя")),
                ("phone", models.CharField(max_length=30, verbose_name="Телефон")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="Марка, модель, год, бюджет, пожелания",
                        verbose_name="Опишите желаемый автомобиль",
                    ),
                ),
                (
                    "consent",
                    models.BooleanField(
                        default=False,
                        verbose_name="Согласие с политикой конфиденциальности",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на поиск авто",
                "verbose_name_plural": "Заявки на поиск авто",
                "ordering": ["-created_at"],
            },
        ),
    ]
