# Generated by Django 5.2.7 on 2026-03-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0003_buyout_request"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Имя")),
                ("phone", models.CharField(max_length=30, verbose_name="Телефон")),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        help_text="Комментарий или пожелания по доставке",
                        verbose_name="Комментарий к заявке",
                    ),
                ),
                (
                    "consent",
                    models.BooleanField(
                        default=False,
                        verbose_name="Согласие с политикой конфиденциальности",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на доставку",
                "verbose_name_plural": "Заявки на доставку",
                "ordering": ["-created_at"],
            },
        ),
    ]
