# Generated by Django 5.2.9 on 2026-04-01 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_registration_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='contact',
            field=models.CharField(blank=True, max_length=255, verbose_name='Telegram'),
        ),
    ]
