# Generated by Django 6.0.3 on 2026-04-01 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_alter_lead_contact_verbose_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertQuestionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема обращения')),
                ('question_type', models.CharField(choices=[('purchase', 'Покупка'), ('service', 'Сервис'), ('other', 'Другое')], default='purchase', max_length=20, verbose_name='Тип вопроса')),
                ('car_brand', models.CharField(blank=True, max_length=255, verbose_name='Марка автомобиля')),
                ('car_model', models.CharField(blank=True, max_length=255, verbose_name='Модель автомобиля')),
                ('message', models.TextField(verbose_name='Описание вопроса')),
                ('consent', models.BooleanField(default=False, verbose_name='Согласие с политикой конфиденциальности')),
            ],
            options={
                'verbose_name': 'Заявка: вопрос эксперту',
                'verbose_name_plural': 'Заявки: вопрос эксперту',
                'ordering': ['-created_at'],
            },
        ),
    ]
