# Generated by Django 6.0.3 on 2026-04-01 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_expertquestionrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotorcycleSalesRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('city', models.CharField(blank=True, max_length=255, verbose_name='Город')),
                ('brand', models.CharField(blank=True, max_length=255, verbose_name='Марка мотоцикла')),
                ('message', models.TextField(blank=True, help_text='Пожелания по модели, бюджету и срокам', verbose_name='Комментарий к заявке')),
                ('consent', models.BooleanField(default=False, verbose_name='Согласие с политикой конфиденциальности')),
                ('vehicle_type', models.CharField(choices=[('car', 'Автомобиль'), ('moto', 'Мотоцикл')], default='moto', max_length=10, verbose_name='Тип транспорта')),
            ],
            options={
                'verbose_name': 'Заявка на продажу мотоциклов',
                'verbose_name_plural': 'Заявки на продажу мотоциклов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='buyoutrequest',
            name='vehicle_type',
            field=models.CharField(choices=[('car', 'Автомобиль'), ('moto', 'Мотоцикл')], default='car', max_length=10, verbose_name='Тип транспорта'),
        ),
        migrations.AddField(
            model_name='carsearchrequest',
            name='vehicle_type',
            field=models.CharField(choices=[('car', 'Автомобиль'), ('moto', 'Мотоцикл')], default='car', max_length=10, verbose_name='Тип транспорта'),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='vehicle_type',
            field=models.CharField(choices=[('car', 'Автомобиль'), ('moto', 'Мотоцикл')], default='car', max_length=10, verbose_name='Тип транспорта'),
        ),
        migrations.AddField(
            model_name='expertquestionrequest',
            name='vehicle_type',
            field=models.CharField(choices=[('car', 'Автомобиль'), ('moto', 'Мотоцикл')], default='car', max_length=10, verbose_name='Тип транспорта'),
        ),
        migrations.AddField(
            model_name='lead',
            name='vehicle_type',
            field=models.CharField(choices=[('car', 'Автомобиль'), ('moto', 'Мотоцикл')], default='car', max_length=10, verbose_name='Тип транспорта'),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='vehicle_type',
            field=models.CharField(choices=[('car', 'Автомобиль'), ('moto', 'Мотоцикл')], default='car', max_length=10, verbose_name='Тип транспорта'),
        ),
    ]
