# Generated by Django 6.0.2 on 2026-02-26 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CookieConsent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "choice",
                    models.CharField(
                        choices=[("accepted", "Принято"), ("rejected", "Отклонено")],
                        max_length=20,
                        verbose_name="Выбор",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=40,
                        verbose_name="Ключ сессии",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата"),
                ),
            ],
            options={
                "verbose_name": "Согласие на cookies",
                "verbose_name_plural": "Согласия на cookies",
                "ordering": ["-created_at"],
            },
        ),
    ]
