# Generated by Django 5.2.7 on 2026-03-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_default_services"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeroMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("image", "Фото"), ("video", "Видео")],
                        default="video",
                        max_length=10,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Используется, если выбран тип «Фото»",
                        null=True,
                        upload_to="hero/%Y/%m/",
                        verbose_name="Фото",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        help_text="Формат MP4. Используется, если выбран тип «Видео»",
                        null=True,
                        upload_to="hero/%Y/%m/",
                        verbose_name="Видео",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фон главного экрана (Hero)",
                "verbose_name_plural": "Фон главного экрана (Hero)",
            },
        ),
    ]
