# Generated by Django 5.2.7 on 2026-03-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_hero_media"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="media_type",
            field=models.CharField(
                choices=[("image", "Фото"), ("video", "Видео")],
                default="image",
                max_length=10,
                verbose_name="Тип медиа",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="video",
            field=models.FileField(
                blank=True,
                help_text="Формат MP4. Используется, если выбран тип «Видео».",
                null=True,
                upload_to="services/%Y/%m/",
                verbose_name="Видео",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Используется, если выбран тип «Фото». Рекомендуемый размер: 600×400 px.",
                null=True,
                upload_to="services/%Y/%m/",
                verbose_name="Фото",
            ),
        ),
    ]
