# Generated by Django 5.2.7 on 2026-03-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_service_media_type_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Краткое описание услуги для списка под блоком «Наши услуги».",
                verbose_name="Описание",
            ),
        ),
    ]
