# Generated by Django 6.0.3 on 2026-03-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_service_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('role', models.CharField(max_length=300, verbose_name='Должность')),
                ('photo', models.ImageField(blank=True, help_text='Рекомендуемый размер: 400×400 px. Если не задано — отображается первая буква имени.', null=True, upload_to='team/%Y/%m/', verbose_name='Фото')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображать')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['order', 'id'],
            },
        ),
    ]
