# Generated by Django 6.0.3 on 2026-03-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например: Kia Sorento, Toyota RAV4', max_length=200, verbose_name='Марка и модель')),
                ('country', models.CharField(choices=[('korea', 'Корея'), ('china', 'Китай'), ('usa', 'США'), ('other', 'Другое')], default='korea', max_length=20, verbose_name='Страна')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год выпуска')),
                ('engine_type', models.CharField(blank=True, help_text='Например: дизель, бензин, электро, гибрид', max_length=100, verbose_name='Тип двигателя')),
                ('description', models.CharField(blank=True, help_text='Доп. текст: «под ключ», «подбор, доставка, оформление» и т.д.', max_length=300, verbose_name='Краткое описание')),
                ('image', models.ImageField(blank=True, help_text='Рекомендуемый размер: 800×500 px.', null=True, upload_to='cases/%Y/%m/', verbose_name='Фото автомобиля')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображать')),
            ],
            options={
                'verbose_name': 'Кейс',
                'verbose_name_plural': 'Кейсы',
                'ordering': ['order', '-id'],
            },
        ),
    ]
