# Generated by Django 6.0.3 on 2026-03-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='media_type',
            field=models.CharField(choices=[('image', 'Фото'), ('video', 'Видео')], default='image', max_length=10, verbose_name='Тип медиа'),
        ),
        migrations.AddField(
            model_name='case',
            name='video',
            field=models.FileField(blank=True, help_text='Формат MP4. Используется при типе «Видео».', null=True, upload_to='cases/%Y/%m/', verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='case',
            name='image',
            field=models.ImageField(blank=True, help_text='Рекомендуемый размер: 800×500 px. Используется при типе «Фото».', null=True, upload_to='cases/%Y/%m/', verbose_name='Фото автомобиля'),
        ),
    ]
