# Generated by Django 6.0.3 on 2026-03-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_case_media_type_case_video_alter_case_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например: Kia K5, Hyundai Santa Fe', max_length=200, verbose_name='Марка и модель')),
                ('country', models.CharField(choices=[('korea', 'Корея'), ('china', 'Китай'), ('usa', 'США'), ('other', 'Другое')], default='korea', max_length=20, verbose_name='Страна')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год выпуска')),
                ('engine_type', models.CharField(blank=True, help_text='дизель, бензин, электро, гибрид', max_length=100, verbose_name='Тип двигателя')),
                ('price', models.CharField(blank=True, help_text='Например: 2 850 000 ₽ или от 2.5 млн ₽', max_length=100, verbose_name='Цена')),
                ('mileage', models.CharField(blank=True, help_text='Например: 25 000 км или Новый', max_length=100, verbose_name='Пробег')),
                ('status', models.CharField(choices=[('available', 'В наличии'), ('in_transit', 'В пути'), ('on_order', 'Под заказ'), ('sold', 'Продано')], default='available', max_length=20, verbose_name='Статус')),
                ('description', models.TextField(blank=True, help_text='Подробности: комплектация, особенности и т.д.', verbose_name='Описание')),
                ('image', models.ImageField(blank=True, help_text='Рекомендуемый размер: 800×500 px.', null=True, upload_to='catalog/%Y/%m/', verbose_name='Фото')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображать')),
            ],
            options={
                'verbose_name': 'Авто в каталоге',
                'verbose_name_plural': 'Каталог авто',
                'ordering': ['order', '-id'],
            },
        ),
    ]
