# Generated by Django 6.0.3 on 2026-03-09 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_catalogcar'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogcar',
            name='video',
            field=models.FileField(blank=True, help_text='Формат MP4. Видеообзор автомобиля.', null=True, upload_to='catalog/%Y/%m/', verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='catalogcar',
            name='image',
            field=models.ImageField(blank=True, help_text='Главное фото для карточки и детальной страницы. 800×500 px.', null=True, upload_to='catalog/%Y/%m/', verbose_name='Главное фото'),
        ),
        migrations.CreateModel(
            name='CatalogCarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='catalog/gallery/%Y/%m/', verbose_name='Фото')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Подпись')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='core.catalogcar', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'Фото галереи',
                'verbose_name_plural': 'Галерея фото',
                'ordering': ['order', 'id'],
            },
        ),
    ]
