# Generated by Django 6.0.3 on 2026-03-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_catalogcar_video_alter_catalogcar_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True, verbose_name='URL')),
                ('excerpt', models.CharField(blank=True, help_text='Показывается в карточке и в превью.', max_length=400, verbose_name='Краткое описание')),
                ('content', models.TextField(help_text='Основной текст. Поддерживаются переносы строк.', verbose_name='Текст статьи')),
                ('image', models.ImageField(blank=True, help_text='Рекомендуемый размер: 800×500 px.', null=True, upload_to='blog/%Y/%m/', verbose_name='Главное фото')),
                ('video', models.FileField(blank=True, help_text='Формат MP4. Опционально.', null=True, upload_to='blog/%Y/%m/', verbose_name='Видео')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Статья блога',
                'verbose_name_plural': 'Блог',
                'ordering': ['-order', '-created_at'],
            },
        ),
    ]
